service: posts
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING, ssm:/primary_db_connection_string}
    PRIMARY_DOMAIN_NAME: ${env:PRIMARY_DOMAIN_NAME, ssm:/primary_domain_name}

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${env:PRIMARY_DOMAIN_NAME, ssm:/primary_domain_name}"
    certificateArn: ${env:PRIMARY_DOMAIN_CERT_ARN, ssm:/primary_domain_cert_arn}
    basePath: "posts"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true

functions:
  getPostsBySubreddit:
    timeout: 30
    handler: index.get_posts_by_subreddit
    logRetentionInDays: 30
    events:
      - http:
          path: /{subreddit}
          method: get
          cors:
            origins:
              - https://${env:PRIMARY_DOMAIN_NAME, ssm:/primary_domain_name}
              - https://www.${env:PRIMARY_DOMAIN_NAME, ssm:/primary_domain_name}
            headers:
              - Content-Type
              - Origin
