service: scraper
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING, ssm:/primary_db_connection_string}
    REDDIT_CLIENT_ID: ${env:REDDIT_CLIENT_ID, ssm:/reddit_client_id}
    REDDIT_SECRET_KEY: ${env:REDDIT_SECRET_KEY, ssm:/reddit_secret_key}
    REDDIT_USERNAME: ${env:REDDIT_USERNAME, ssm:/reddit_username}
    REDDIT_PASSWORD: ${env:REDDIT_PASSWORD, ssm:/reddit_password}

functions:
  fetchPosts:
    timeout: 30
    memorySize: 256
    handler: index.fetchPosts
    logRetentionInDays: 7
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: politics
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: worldnews
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: europe
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: news
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: technology
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: science
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: health
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: environment
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: energy
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: sports
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: business
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            subreddit: Economics
